name: Practica 1 - Secretos y Variables

on:
  push:
    branches: [ "main" ]

jobs:
  probar-conexion:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Probar app inyectando secretos
        # Inyectamos variables de entorno y secretos aquí
        env:
          ENTORNO: 'Pruebas-QA'
          DB_PASS: ${{ secrets.PASSWORD_BD }}
        run: node app.js
